### ISSUE TITLE
Consider making jets/flights a core feature

### ISSUE THREAD

**Issue by rglassett** [akliu/takeoff#2]
It's easy to see how implementing jets and flights could get very complicated, but I think your app needs at least some form of this to be interesting. Consider a basic implementation like this:
- Jets belong to users
- Owners register their jet at an airport
- Travelers select a jet when booking a reservation

As bonuses, jets might have different prices, ratings, reviews, photos, comments, etc. Don't worry too much about making actual route tables with schedules, that's probably overdoing it. Shoot for features that would be fun to write and to use; the sky's the limit here.

**Comment by akliu** [comment]
Added a Jets table and the ability for owners to register their jets and travelers to select a specific jet as a core feature (phase 5).  I have also listed additional jet features as bonuses.
